src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VATRegistrationNumber__c</fullName>
        <label>VAT Registration Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bill__c.object
<CustomObject>
    <fields>
        <fullName>BillDate__c</fullName>
        <description>This is the Date that the Bill was generated on.</description>
        <label>Bill Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BilledAmount__c</fullName>
        <description>Sum of all Bill items - calculated in Heroku</description>
        <label>Billed Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ContractNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Number</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Bills</relationshipLabel>
        <relationshipName>Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomerNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will be the value that is stored against the customer autonumber (custref) may not need this as we will link with the id on the customer account.  Could be against a void property but would this still have a customer? These are only read/ write due to customer moves ...same for a few fields below</description>
        <label>Account Number</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bills</relationshipLabel>
        <relationshipName>BillStatementCreditNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalDue__c</fullName>
        <description>Billed amount +/- payments/adjustments</description>
        <label>Total Due</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bill</label>
    <nameField>
        <label>Bill</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BillItem__c.object
<CustomObject>
    <fields>
        <fullName>BillItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill Item</label>
        <referenceTo>BillItem__c</referenceTo>
        <relationshipLabel>Bill Items</relationshipLabel>
        <relationshipName>BillItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BillServiceType__c</fullName>
        <label>Bill Service Type</label>
        <referenceTo>BillServiceType__c</referenceTo>
        <relationshipLabel>Bill Items</relationshipLabel>
        <relationshipName>BillItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BilledAmount__c</fullName>
        <description>Amount Returned from Heroku</description>
        <label>Billed Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NumberOfDays__c</fullName>
        <description>From - To (return days) Number of days that this bill item exists for. 
Display days for Bill Item</description>
        <formula>To__c  -  From__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RateBand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Band</label>
        <referenceTo>RateBand__c</referenceTo>
        <relationshipName>BillItemsCreditItem</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Bill Items</relationshipLabel>
        <relationshipName>BillItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceItem__c</fullName>
        <label>Service Item</label>
        <referenceTo>ServiceItem__c</referenceTo>
        <relationshipLabel>Bill Items</relationshipLabel>
        <relationshipName>BillItemsCreditItem</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>VolumeUsed__c</fullName>
        <description>Device consumption or Value used to calculated this charge line.
Measured</description>
        <label>Volume Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bill Item</label>
    <nameField>
        <label>Bill Items</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BillServiceType__c.object
<CustomObject>
    <fields>
        <fullName>Bill__c</fullName>
        <label>Bill</label>
        <referenceTo>Bill__c</referenceTo>
        <relationshipName>BillServicesTypes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Type</label>
        <referenceTo>ServiceType__c</referenceTo>
        <relationshipName>BillServicesTypes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bill Service Type</label>
    <nameField>
        <label>Bill Service Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill Service Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>BillingAddress__c</fullName>
        <description>Pre-populate the field from Billing Address on Customer. Allow the user to overwrite.</description>
        <label>Billing Address</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BillingFrequency__c</fullName>
        <description>This field differentiate the frequency of Billing life cycle.</description>
        <label>Billing Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Six Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>CON-{00000000}</displayFormat>
        <label>Contract Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PaymentPlan__c.object
<CustomObject>
    <fields>
        <fullName>ContractOrder__c</fullName>
        <description>Look up to Contract</description>
        <label>Contract/Order</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>PaymentPlans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <label>Day Of Week</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <displayFormat>PPN-{0000000000}</displayFormat>
        <label>Payment Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RateBand__c.object
<CustomObject>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Rate Bands</relationshipLabel>
        <relationshipName>RateBands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rate Band</label>
    <nameField>
        <label>Rate Band Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Bands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service__c.object
<CustomObject>
    <description>This is the high level family of a service provided to a customer under a contract (e.g. Water, Sewerage, Electricity, Gas etc.)</description>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Service Type object</description>
        <label>Service Type</label>
        <referenceTo>ServiceType__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BlIn_PDFXMLDefinition.cls
/******************************************************************************
@author    		Accenture: Patrick Dixon
@date      		15 Sep 2017
@description 	Class to define the objects, fields and relationships that will 
				be used to construct the PDF XML data records submitted to the  
				the PDF generation webservice
*******************************************************************************/
public with sharing class BlIn_PDFXMLDefinition {
	
	// list of XMLObjects used to generate the PDF data
	public List<BlIn_PDFBillData.XMLObject> XMLObjects;
	
	/******************************************************************************
	@author    		Accenture: Patrick Dixon
	@date      		15 Sep 2017
	@description 	Constructor
	*******************************************************************************/
	public BlIn_PDFXMLDefinition() {
    	
    	// define a list of XML objects
		XMLObjects = new List<BlIn_PDFBillData.XMLObject>{
		
			/* Bill */
			new BlIn_PDFBillData.XMLObject(
			
					'Bill__c', 				/* Object API name */
					null, 					/* Parent object API name */
					null, 					/* Parent Id field */
					new Set<String>{		/* Id fields used to match object records*/
									'CustomerNumber__c', 		// Account
									'ContractNumber__c' 		// Contract__c
									}, 
					new Set<String>{		/* XML fields */
									'BillDate__c', 
									'Name', 
									'TotalDue__c' 
									} 
					),
		
			/* Bill Items */
			new BlIn_PDFBillData.XMLObject(
			
					'BillItem__c', 				/* Object API name */
					'Bill__c', 					/* Parent object API name */
					'BillServiceType__r.Bill__c', 					/* Parent Id field */
					new Set<String>(),			/* Id fields used to match object records*/
					new Set<String>{		/* XML fields */
									'ServiceItem__r.Name', 
									'VolumeUsed__c', 
									'NumberOfDays__c', 
									'RateBand__r.Rate__c', 
									'BilledAmount__c'//, 
//									'VATAmount__c' 
									} 
					),
		
			/* Account */
			new BlIn_PDFBillData.XMLObject(
			
					'Account', 				/* Object API name */
					null, 					/* Parent object API name */
					null, 					/* Parent Id field */
					new Set<String>(), 		/* Id fields used to match object records*/
					new Set<String>{		/* XML fields */
									'Email__c', 
									'Fax', 
									'Website', 
									'VATRegistrationNumber__c' 
									} 	
					),

			/* Contract */
			new BlIn_PDFBillData.XMLObject(
			
					'Contract__c', 			/* Object API name */
					null, 					/* Parent object API name */
					null, 					/* Parent Id field */
					new Set<String>(), 		/* Id fields used to match object records*/
					new Set<String>{		/* XML fields */
									'Name', 
									'BillingAddress__c', 
									'BillingFrequency__c'  
									} 
					),

			/* Payment Plans */
			new BlIn_PDFBillData.XMLObject(
			
					'PaymentPlan__c', 			/* Object API name */
					'Contract__c', 			/* Parent object API name */
					'ContractOrder__c', 			/* Parent Id field */
					new Set<String>(), 		/* Id fields used to match child object records*/
					new Set<String>{		/* XML fields */
									'DayOfWeek__c',
									'DayOfMonth__c', 
									'PaymentFrequency__c', 
									'PaymentPlanType__r.Name', 
									'PlanAmount__c', 
									'StartDate__c'  
									} 
					),

			/* Services */
			new BlIn_PDFBillData.XMLObject(
			
					'Service__c', 			/* Object API name */
					'Contract__c', 			/* Parent object API name */
					'Contract__c', 			/* Parent Id field */
					new Set<String>{ 		/* Id fields used to match child object records*/
									'Device__c', 		// Device__c
									'SupplyPoint__c'		// SupplyPoint__c
									}, 
					new Set<String>{		/* XML fields */
									'ServiceType__r.Name',
									'Device__r.SerialNo__c', 
									'SupplyPoint__r.Location__r.PostalZIPCode__c'  
									} 
					),

			/* Readings */
			new BlIn_PDFBillData.XMLObject(
			
					'Reading__c', 			/* Object API name */
					'Service__c', 			/* Parent object API name */
					'DeviceReference__c', 	/* Parent Id field */
					new Set<String>(), 		/* Id fields used to match child object records*/
					new Set<String>{		/* XML fields */
									'ActualDeviceReading__c', 
									'DeviceReference__r.SerialNo__c', 
									'GrossConsumption__c', 
									'Reading__c', 
									'ReadingDate__c', 
									'ReadingType__c'  
									} 
					)
		};
	}
}