src/objects/AverageDailyUse__c.object
<CustomObject>
    <fields>
        <fullName>AverageDailyUsage__c</fullName>
        <label>Average Daily Usage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SupplyPointDevice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supply Point Device</label>
        <referenceTo>SupplyPointDevice__c</referenceTo>
        <relationshipLabel>Average Daily Usage</relationshipLabel>
        <relationshipName>AverageDailyUsage</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Average Daily Use</label>
    <nameField>
        <displayFormat>ADU-{000000000}</displayFormat>
        <label>Average Daily Usage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Average Daily Usage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Device__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <formula>NumberOfActiveSupplyPointDevice__c  = 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DeviceReference__c</fullName>
        <formula>Name &amp;TEXT(  DeviceValidation__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Device Reference</label>
        <type>Text</type>
    </fields>
    <label>Device</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Device Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reading__c.object
<CustomObject>
    <fields>
        <fullName>ActualDeviceReading__c</fullName>
        <description>Device Reading</description>
        <label>Actual Device Reading</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DeviceReference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Device Reference</label>
        <referenceTo>Device__c</referenceTo>
        <relationshipLabel>Readings</relationshipLabel>
        <relationshipName>Readings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReadingDate__c</fullName>
        <label>Reading Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reading__c</fullName>
        <formula>IF(ISPICKVAL(DeviceReference__r.DeviceType__r.UnitOfMeasure__c,&apos;Imperial - UK Gallons&apos;), 
 IF(ISBLANK(DeviceReference__r.DeviceType__r.Multiplier__c),(ActualDeviceReading__c / 1000)*0.22,(ActualDeviceReading__c / 1000)*0.22*DeviceReference__r.DeviceType__r.Multiplier__c)
 ,IF(ISBLANK(DeviceReference__r.DeviceType__r.Multiplier__c),ActualDeviceReading__c,ActualDeviceReading__c *DeviceReference__r.DeviceType__r.Multiplier__c))</formula>
        <label>Reading</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Reading</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Reading Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SupplyPointDevice__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <description>1. IF Today is greater than Installation date and Removal Date is BLANK, then Active
2. IF Removal Date is not BLANK and Instalment Date &lt;=TODAY&lt;=Removal Date, then Active
ELSE Inactive</description>
        <formula>AND(InstallationDate__c  &lt;=  TODAY(),RemovalDate__c  &gt;=  TODAY())  ||   AND( TODAY()  &gt;=  InstallationDate__c,ISBLANK(RemovalDate__c) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Device__c</fullName>
        <label>Device</label>
        <referenceTo>Device__c</referenceTo>
        <relationshipLabel>Supply Point Devices</relationshipLabel>
        <relationshipName>SupplyPointDevices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Supply Point Device</label>
    <nameField>
        <displayFormat>SPD-{000000000}</displayFormat>
        <label>Supply Point Device Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Point Devices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GlUt_ReadingHandler.cls
/***************************************************************************************************
@author        Accenture : Manish Singh
@date          04-Sep-2017
@description:  This is helper class used by Reading object trigger  
@group         TriggerHelper
*******************************************************************************************************/
public with sharing class GlUt_ReadingHandler extends GlUt_TriggerHandlerBase{
    // Variable declaration
    
    // End variable declaration
    
    /**********************************************************************************************
    @author        Accenture: Manish Singh
    @date          04-Sep-2017
    @param         GlUt_TriggerHandlerObj inputParam
    @return        void
    @description   This method is used to invoke method from trigger
    **********************************************************************************************/
    public override void  MainEntry(GlUt_TriggerHandlerObj inputParam){
        try{
        //Logger.Push('MainEntry', 'BlAp_ReadingHandler');
            if( inputParam.isInsert && inputParam.isBefore ){
                    
            }
            if( inputParam.isInsert && inputParam.isAfter ){
                // call for average daily uses calculations 
                calAvgDailyUses(inputParam.newlist);
                
            }
            if( inputParam.isUpdate && inputParam.isBefore ){
                
            }
            if( inputParam.isUpdate && inputParam.isAfter ){
                    
            }  
            if( inputParam.isDelete && inputParam.isBefore ){
                
            }
            if( inputParam.isDelete && inputParam.isAfter ){
            
            }  
        }
        catch (Exception ex){
            system.debug('Line Number:=' + ex.getLineNumber());
                //Logger.debugException(ex);
        }

        finally{   
            //Reset the active function to null in case this class was first in stack
            //this indicates that the trigger has finished firing so it no longer needs to control flow
            GlUt_CentralDispatcher.activeFunction = null;
            //Logger.pop();
        }
    
            //update inputParam.newlist;
    }
    /**********************************************************************************************
    @author        Accenture: Manish Singh
    @date          05-Sep-2017
    @param         Trigger.new
    @return        void
    @description   This method is used to calculate daily uses for device
    **********************************************************************************************/
    private void calAvgDailyUses(list<Reading__c> newlist){
        set<Id> setDeviceId = new set<Id>();
        list<AverageDailyUse__c> listAverageUses = new list<AverageDailyUse__c>() ;
        map<Id,list<Reading__c>> mapDeviceReading = new map<Id,list<Reading__c>>() ;
        map<Id,list<SupplyPointDevice__c>> mapDeviceSupplyptDevice = new map<Id,list<SupplyPointDevice__c>>();
        for(Reading__c read : newlist){
            setDeviceId.add(read.DeviceReference__c);
        }
        
        for(Device__c device: [Select Id, (select Id, ActualDeviceReading__c, DeviceReference__c,ReadingDate__c  from 
            Readings__r order by createdDate desc limit :GlUt_Constants.LIMITBILLINGCAL ),(select Id from 
            SupplyPointDevices__r where Active__c = true limit 1) from Device__c where Id=:setDeviceId ]){
            if(device.Readings__r != null)
                mapDeviceReading.put(device.Id,device.Readings__r);
            if(!device.SupplyPointDevices__r.isEmpty() && device.SupplyPointDevices__r != null )
                mapDeviceSupplyptDevice.put(device.Id,device.SupplyPointDevices__r);        
        }
        if(mapDeviceReading != null && !mapDeviceReading.isEmpty()){
            double readingDifference ;
            integer daysDifference = GlUt_Constants.INDEX1;
            for(Id deviceId: mapDeviceReading.keySet() ){
                readingDifference = mapDeviceReading.get(deviceId)[GlUt_Constants.INDEX0].ActualDeviceReading__c - 
                    mapDeviceReading.get(deviceId)[GlUt_Constants.INDEX1].ActualDeviceReading__c;
               datetime startDateTime = mapDeviceReading.get(deviceId)[GlUt_Constants.INDEX1].ReadingDate__c;
               datetime endDateTime = mapDeviceReading.get(deviceId)[GlUt_Constants.INDEX0].ReadingDate__c;
                date startDate = Date.newinstance(startDateTime.year(), startDateTime.month(),startDateTime.day());
                date endDate =  Date.newinstance(endDateTime.year(), endDateTime.month(),endDateTime.day());
                daysDifference = startDate.daysBetween(endDate);
                daysDifference  = daysDifference == GlUt_Constants.INDEX0 ? GlUt_Constants.INDEX1 : daysDifference ;                                       
                system.debug('@@@readingDifferenc = '+ readingDifference + ' @@@daysDifference ='+daysDifference);
                double averageReading = readingDifference/daysDifference;
                if(mapDeviceSupplyptDevice.containsKey(deviceId)){                    
                    if( mapDeviceSupplyptDevice.get(deviceId)[GlUt_Constants.INDEX0].Id != null)
                        listAverageUses.add(new AverageDailyUse__c(AverageDailyUsage__c = averageReading,Date__c= System.Today(),
                            SupplyPointDevice__c =mapDeviceSupplyptDevice.get(deviceId)[GlUt_Constants.INDEX0].Id));
                }            
            }
        }
        if(!listAverageUses.isEmpty() && listAverageUses!= null){
            database.insert(listAverageUses);
        }
    }
}