src/objects/AverageDailyUse__c.object
<CustomObject>
    <fields>
        <fullName>SupplyPointDevice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supply Point Device</label>
        <referenceTo>SupplyPointDevice__c</referenceTo>
        <relationshipLabel>Average Daily Usage</relationshipLabel>
        <relationshipName>AverageDailyUsage</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Average Daily Use</label>
    <nameField>
        <displayFormat>ADU-{000000000}</displayFormat>
        <label>Average Daily Usage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Average Daily Usage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>CON-{00000000}</displayFormat>
        <label>Contract Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Device__c.object
<CustomObject>
    <fields>
        <fullName>DeviceType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent-child relationship with Device Type.</description>
        <label>Device Type</label>
        <referenceTo>DeviceType__c</referenceTo>
        <relationshipLabel>Devices</relationshipLabel>
        <relationshipName>Devices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Device</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Device Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DeviceType__c.object
<CustomObject>
    <label>Device Type</label>
    <nameField>
        <label>Device Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Device Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>LocationSubType__c</fullName>
        <description>Dependent on Location Type</description>
        <label>Location Sub Type</label>
        <picklist>
            <controllingField>LocationType__c</controllingField>
            <picklistValues>
                <fullName>Detached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi detached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terraced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Croft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Sector</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Match to salesforce Address format</description>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <label>Location</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reading__c.object
<CustomObject>
    <fields>
        <fullName>ActualDeviceReading__c</fullName>
        <description>Device Reading</description>
        <label>Actual Device Reading</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ReadingDate__c</fullName>
        <label>Reading Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reading__c</fullName>
        <formula>IF(ISPICKVAL(DeviceReference__r.DeviceType__r.UnitOfMeasure__c,&apos;Imperial - UK Gallons&apos;), 
 IF(ISBLANK(DeviceReference__r.DeviceType__r.Multiplier__c),(ActualDeviceReading__c / 1000)*0.22,(ActualDeviceReading__c / 1000)*0.22*DeviceReference__r.DeviceType__r.Multiplier__c)
 ,IF(ISBLANK(DeviceReference__r.DeviceType__r.Multiplier__c),ActualDeviceReading__c,ActualDeviceReading__c *DeviceReference__r.DeviceType__r.Multiplier__c))</formula>
        <label>Reading</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Reading</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Reading Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SupplyPoint__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Supply Points</relationshipLabel>
        <relationshipName>SupplyPoints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Measured__c</fullName>
        <label>Measured</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ReadFrequency__c</fullName>
        <description>Read Frequency will vary with clients so will need updating at implementation.</description>
        <label>Read Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Four Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unmeasured</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Supply Point</label>
    <nameField>
        <displayFormat>SP-{000000000}</displayFormat>
        <label>Supply Point Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SupplyPointDevice__c.object
<CustomObject>
    <fields>
        <fullName>Device__c</fullName>
        <label>Device</label>
        <referenceTo>Device__c</referenceTo>
        <relationshipLabel>Supply Point Devices</relationshipLabel>
        <relationshipName>SupplyPointDevices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ReadFrequency__c</fullName>
        <description>Created as per JIRA task AT-295 to fetch Read Frequency from parent Supply Point.</description>
        <formula>TEXT( SupplyPoint__r.ReadFrequency__c )</formula>
        <label>Read Frequency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SupplyPoint__c</fullName>
        <label>Supply Point</label>
        <referenceTo>SupplyPoint__c</referenceTo>
        <relationshipLabel>Supply Point Devices</relationshipLabel>
        <relationshipName>Supply_Point_Devices</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Supply Point Device</label>
    <nameField>
        <displayFormat>SPD-{000000000}</displayFormat>
        <label>Supply Point Device Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Point Devices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GlUt_ReadingHandler_Test.cls
/******************************************************************************
@author:      Accenture: Manish Singh
@date:        07 September 2017
@description: Test Class for GlUt_ReadingHandler
*******************************************************************************/
@isTest
Public Class GlUt_ReadingHandler_Test{
    private static string accountName1 = 'Test Account1';
    private static string contractName = 'Test Contract';
    private static string testDeviceType = 'TestDeviceType';
    private static string testsubDevice =    'TestsubDevice';
    private static string testServiceType ='TestServiceType';
    private static string location= 'A99 9AA';
    private static string detached = 'Detached';
    private static string customerName = 'Test customer';
    private static string STRTEST ='test';
    private static string measured= 'measured';
    private static string YES = 'yes';
    private static string DEVICENAME= 'TestDeviceName';
    private static User dummyUser;
    private static integer actualReading = 20;
    private static integer actualDeviceReading = 120;
    private static integer readingDate = 12;
    private static integer listSize = 200;
    private static integer listStart = 0;
    private static integer dailyUseInsertedSize = 1;
    public static String profileName = 'System Administrator';
    public static String userName = 'TestUser';
    
    /*******************************************************************
    Purpose: method to create test data used by all test methods
    Parameters: N/A 
    Returns: void
    Throws [Exceptions]: N/A
    ********************************************************************/    
    @TestSetup
    Static void createTestData(){  

        User objUser = GlUt_TestFactoryData.createUser(profileName,userName,null);
        Database.insert(objUser);
        
        Account objAccount = GlUt_TestFactoryData.CreateAccount(accountName1);
        Database.insert(objAccount);
        Contract__c objContract = GlUt_TestFactoryData.CreateContract(contractName ,objAccount);
        Database.insert(objContract);
        DeviceType__c  objDeviceType = GlUt_TestFactoryData.CreateDeviceType(testDeviceType );
        Database.insert(objDeviceType);        
        Location__c objLocation = GlUt_TestFactoryData.CreateLocation(location);
        objLocation.LocationSubType__c=detached ; 
        objLocation.Street__c =STRTEST ;
        Database.insert(objLocation);
        list<Device__c > listDevice = new list<Device__c >();
            for(integer i=listStart; i<listSize; i++){
                listDevice.add(GlUt_TestFactoryData.CreateDevice(DEVICENAME,objDeviceType) );
            }
        Database.insert(listDevice);
        SupplyPoint__c  objSupplyPoint = GlUt_TestFactoryData.CreateSupplyPoint(objLocation);
        objSupplyPoint.Measured__c=YES;
        objSupplyPoint.ReadFrequency__c =measured;
        Database.insert(objSupplyPoint);
        list<Reading__c> listReading = new list<Reading__c>();
        list<SupplyPointDevice__c > listSupplyPointDevice = new list<SupplyPointDevice__c >();
        for(integer i=listStart; i<listSize; i++){
            listSupplyPointDevice.add(GlUt_TestFactoryData.CreateSupplyPointDevices(listDevice[i], objSupplyPoint ));
            Reading__c  objReading = GlUt_TestFactoryData.CreateReading(listDevice[i]);
            objReading.ActualDeviceReading__c= actualReading;
            objReading.ReadingDate__c = Date.today();
            listReading.add(objReading);
        }
        
        Database.insert(listSupplyPointDevice);
        Database.insert(listReading);
        
    }
    
    /*******************************************************************
    Purpose: Bulk testing Method to insert average daily uses records while 
             new reading is captured.
    Parameters: N/A 
    Returns: void
    Throws [Exceptions]: N/A
    ********************************************************************/
    static testmethod void calAvgDailyUses_Bulk(){
        User dummyUser = [select id,name from user where isActive=true limit 1];
        system.runAs(dummyUser){
            list<Device__c> listDevice = new list<Device__c>([Select Id from Device__c]); 
            list<Reading__c> listReading = new List<Reading__c>();           
            Test.startTest();
            for(integer i=listStart; i<listSize; i++){
                Reading__c  objReading = GlUt_TestFactoryData.CreateReading(listDevice[i]);
                objReading.ActualDeviceReading__c= actualDeviceReading;
                objReading.ReadingDate__c = Date.today()+readingDate;
                listReading.add(objReading);
            }
            Database.insert(listReading);      
            
            list<AverageDailyUse__c> listDailyUse = [Select Id from AverageDailyUse__c ];
            Test.StopTest();
            system.assertEquals(listDailyUse .size(), listSize);
        }
    }
    
    /*******************************************************************
    Purpose: Method to insert average daily uses records while new reading is captured.
             {Positive scenario}
    Parameters: N/A 
    Returns: void
    Throws [Exceptions]: N/A
    ********************************************************************/
    static testmethod void calAvgDailyUses_Positive(){
        User dummyUser =[select id,name from user where isActive=true limit 1];
        system.runAs(dummyUser){            
            Device__c device = [Select Id from Device__c limit 1];            
            Test.startTest();
            Reading__c  objReading = GlUt_TestFactoryData.CreateReading(device );
            objReading.ActualDeviceReading__c= actualDeviceReading;
            objReading.ReadingDate__c = Date.today()+readingDate; 
            Database.insert(objReading);
            GlUt_TriggerHandlerObj dataHandler = new GlUt_TriggerHandlerObj();
            GlUt_ReadingHandler readingHandler = new GlUt_ReadingHandler();
            Test.StopTest();
            list<AverageDailyUse__c> listDailyUse = [Select Id from AverageDailyUse__c ];
            system.assertEquals(listDailyUse.size(), dailyUseInsertedSize);
        }
    }
}