src/objects/Bill__c.object
<CustomObject>
    <fields>
        <fullName>BillCalculation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>18 Sep 2017, P Dixon - lookup to bill calculation record created if this bill was calculated as part of a manual request</description>
        <label>Bill Calculation</label>
        <referenceTo>BillCalculation__c</referenceTo>
        <relationshipLabel>Bills</relationshipLabel>
        <relationshipName>Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BillDate__c</fullName>
        <description>This is the Date that the Bill was generated on.</description>
        <label>Bill Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BilledAmount__c</fullName>
        <description>Sum of all Bill items - calculated in Heroku</description>
        <label>Billed Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ContractGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>linked to a contract</description>
        <label>Contract Group</label>
        <referenceTo>ContractGroup__c</referenceTo>
        <relationshipName>BillStatementCreditNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Number</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Bills</relationshipLabel>
        <relationshipName>Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomerNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will be the value that is stored against the customer autonumber (custref) may not need this as we will link with the id on the customer account.  Could be against a void property but would this still have a customer? These are only read/ write due to customer moves ...same for a few fields below</description>
        <label>Account Number</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bills</relationshipLabel>
        <relationshipName>BillStatementCreditNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HerokuPostgresId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>20 Sep 2017, P Dixon - external id for Heroku mastered objects</description>
        <externalId>true</externalId>
        <label>Heroku Postgres Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TotalDue__c</fullName>
        <description>Billed amount +/- payments/adjustments</description>
        <label>Total Due</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bill</label>
    <nameField>
        <label>Bill</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BillCalculation__c.object
<CustomObject>
    <label>Bill Calculation</label>
    <nameField>
        <displayFormat>BC-{00000000}</displayFormat>
        <label>Bill Calculation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BillItem__c.object
<CustomObject>
    <fields>
        <fullName>BillItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill Item</label>
        <referenceTo>BillItem__c</referenceTo>
        <relationshipLabel>Bill Items</relationshipLabel>
        <relationshipName>BillItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BillServiceType__c</fullName>
        <label>Bill Service Type</label>
        <referenceTo>BillServiceType__c</referenceTo>
        <relationshipLabel>Bill Items</relationshipLabel>
        <relationshipName>BillItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BilledAmount__c</fullName>
        <description>Amount Returned from Heroku</description>
        <label>Billed Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <description>Day After previous bill Item &quot;to&quot; date.</description>
        <label>From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HerokuPostgresId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>20 Sep 2017, P Dixon - external id for Heroku mastered objects</description>
        <externalId>true</externalId>
        <label>Heroku Postgres Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RateBand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Band</label>
        <referenceTo>RateBand__c</referenceTo>
        <relationshipName>BillItemsCreditItem</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reading__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reading</label>
        <referenceTo>Reading__c</referenceTo>
        <relationshipName>BillItemsCreditItem</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceItem__c</fullName>
        <label>Service Item</label>
        <referenceTo>ServiceItem__c</referenceTo>
        <relationshipLabel>Bill Items</relationshipLabel>
        <relationshipName>BillItemsCreditItem</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <description>Last day of Bill Item</description>
        <label>To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>VolumeUsed__c</fullName>
        <description>Device consumption or Value used to calculated this charge line.
Measured</description>
        <label>Volume Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bill Item</label>
    <nameField>
        <label>Bill Items</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BillServiceType__c.object
<CustomObject>
    <fields>
        <fullName>Bill__c</fullName>
        <label>Bill</label>
        <referenceTo>Bill__c</referenceTo>
        <relationshipName>BillServicesTypes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HerokuPostgresId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>20 Sep 2017, P Dixon - external id for Heroku mastered objects</description>
        <externalId>true</externalId>
        <label>Heroku Postgres Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ServiceType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Type</label>
        <referenceTo>ServiceType__c</referenceTo>
        <relationshipName>BillServicesTypes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bill Service Type</label>
    <nameField>
        <label>Bill Service Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill Service Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>BillCalculation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>18 Sep 2017, P Dixon - lookup to bill calculation request record to track whether a manual bill calculation has been requested</description>
        <label>Bill Calculation</label>
        <referenceTo>BillCalculation__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Group</label>
        <referenceTo>ContractGroup__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomerName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the Customer</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>CON-{00000000}</displayFormat>
        <label>Contract Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ContractGroup__c.object
<CustomObject>
    <label>Contract Group</label>
    <nameField>
        <label>Contract Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RateBand__c.object
<CustomObject>
    <label>Rate Band</label>
    <nameField>
        <label>Rate Band Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Bands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reading__c.object
<CustomObject>
    <fields>
        <fullName>Reading__c</fullName>
        <formula>IF(ISPICKVAL(DeviceReference__r.DeviceType__r.UnitOfMeasure__c,&apos;Imperial - UK Gallons&apos;), 
 IF(ISBLANK(DeviceReference__r.DeviceType__r.Multiplier__c),(ActualDeviceReading__c / 1000)*0.22,(ActualDeviceReading__c / 1000)*0.22*DeviceReference__r.DeviceType__r.Multiplier__c)
 ,IF(ISBLANK(DeviceReference__r.DeviceType__r.Multiplier__c),ActualDeviceReading__c,ActualDeviceReading__c *DeviceReference__r.DeviceType__r.Multiplier__c))</formula>
        <label>Reading</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Reading</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Reading Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceItem__c.object
<CustomObject>
    <description>&quot;This is a &apos;charge&apos; item for a particular service provided to a Customer under a Contract 
(e.g. Water Volume, Fixed Charge, Sewage Volume)
The level at which Bill Items will be generated for. This has a link to the Service Item Type &quot;</description>
    <label>Service Item</label>
    <nameField>
        <displayFormat>SIN-{000000}</displayFormat>
        <label>Service Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ServiceType__c.object
<CustomObject>
    <description>This is a group for the type of charges. Water or Sewage or Trade Effluent</description>
    <label>Service Type</label>
    <nameField>
        <label>Service Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BlIn_BillCalcResponseContainer.cls
/******************************************************************************
@author    		Accenture: Patrick Dixon
@date      		01 Sep 2017
@description 	Container class for JSON billing response
*******************************************************************************/
public with sharing class BlIn_BillCalcResponseContainer {

	public static final String CLASS_NAME = 'BlIn_BillCalcResponseContainer';
	public static final String DEBUG = '[' + CLASS_NAME + '] ';
	
	// Bill Calculation
	public String Status;
	public List<BlIn_BillCalcResponseBillObj> Bills;

	// Bill
	/******************************************************************************
	@author    		Accenture: Patrick Dixon
	@date      		01 Sep 2017
	@description 	Subclass for Bill JSON Object
	*******************************************************************************/
	public class BlIn_BillCalcResponseBillObj {

		public String Id;
		public String Name;
		public String AccountId;
		public String ContractId;
		public String ContractGroupId;
		public String OriginalBillId;
		public String BilledAmount;
		public String TotalDue;
		public List<BlIn_BillCalcResponseBillServiceTypeObject> BillServiceTypes;
	}

	// Bill Services
	/******************************************************************************
	@author    		Accenture: Patrick Dixon
	@date      		20 Sep 2017
	@description 	Subclass for Bill Services Type JSON Object
	*******************************************************************************/
	public class BlIn_BillCalcResponseBillServiceTypeObject {

		public String Id;
		public String Name;
		public String ServiceTypeId;
		public List<BlIn_BillCalcResponseBillItemObject> BillItems;
	}
    
	// Bill Items
	/******************************************************************************
	@author    		Accenture: Patrick Dixon
	@date      		01 Sep 2017
	@description 	Subclass for Bill Item JSON Object
	*******************************************************************************/
	public class BlIn_BillCalcResponseBillItemObject {

		public String Id;
		public String Name;
		public String ServiceItemId;		// Required
		public String BillItemId; 
		public String RateBandId; 
		public String ReadingId; 
		public String VolumeUsed;
		public String ChargeBasisValue;
		public String FromDate;
		public String ToDate;
		public String BilledAmount;
	}
    
	/******************************************************************************
	@author    		Accenture: Patrick Dixon
	@date      		01 Sep 2017
	@param			String - json
	@return			BlIn_BillCalcResponseContainer - formatted billing object
	@description 	parses and formats the JSON response 
	*******************************************************************************/
    public static BlIn_BillCalcResponseContainer parse(String json) {

        return (BlIn_BillCalcResponseContainer) System.JSON.deserialize(json, BlIn_BillCalcResponseContainer.class);
    }
    
	/******************************************************************************
	@author    		Accenture: Patrick Dixon
	@date      		20 Sep 2017
	@param			Id - bill calculation Id
	@param			BlIn_BillCalcResponseContainer - formatted billing object
	@return			List<Id> - bill Ids (null if the bill result was not ready)
	@description 	builds and inserts the records 
	*******************************************************************************/
    public static List<Id> processResult(Id billCalculationId, BlIn_BillCalcResponseContainer result) {	

		system.debug(DEBUG + 'result: ' + result);
		
		// TO-DO - temp for debug
		String rand = String.valueOf(Datetime.now());
		Id accountId;
		Id contractId;
		for (BillCalculation__c billcalculation : [select Id, (select Id, CustomerName__c from Contracts__r) from BillCalculation__c where Id = :billCalculationId]) {
			for (Contract__c contract : billcalculation.Contracts__r) {
				contractId = contract.Id;
				accountId = contract.CustomerName__c;
				break;
			}
			break;
		}
		// END temp for debug
		
    	if (result.Status == BlIn_Constants.BILL_CALCULATION_STATUS_COMPLETED) {
			List<Bill__c> billsInserted = new List<Bill__c>();
    		
    		List<SObject> recordsToInsert = new List<SObject>();
    		for (BlIn_BillCalcResponseBillObj billObj : result.Bills) {
    			
    			Bill__c billReference = new Bill__c(HerokuPostgresId__c = billObj.Id + rand);
    			Bill__c bill = (new Bill__c(
	   										Name = billObj.Name, 
											BillCalculation__c = (Id)billCalculationId, 
											HerokuPostgresId__c = billObj.Id + rand, 
											BillDate__c = Date.today(),		// TO-DO
											CustomerNumber__c = accountId,		//(Id)billObj.AccountId, 
											ContractNumber__c = contractId,		//(Id)billObj.ContractId, 												
//											ContractGroup__c = (Id)billObj.ContractGroupId, 
//											OriginalBill__c = (Id)billObj.OriginalBillId, 
											BilledAmount__c = Decimal.valueOf(billObj.BilledAmount), 
											TotalDue__c = Decimal.valueOf(billObj.TotalDue)
											)
									);
    			recordsToInsert.add(bill);

				// add the bill to the list of bills inserted				
				billsInserted.add(bill);
				
				for (BlIn_BillCalcResponseBillServiceTypeObject billServiceTypeObj : billObj.BillServiceTypes) {
					
	    			BillServiceType__c billServiceTypeReference = new BillServiceType__c(HerokuPostgresId__c = billServiceTypeObj.Id + rand);
    				recordsToInsert.add(new BillServiceType__c(
    															Name = billServiceTypeObj.Name, 
																Bill__r = billReference, 
																HerokuPostgresId__c = billServiceTypeObj.Id + rand//, 
//																ServiceType__c = (Id)billServiceTypeObj.ServiceTypeId 
																)
										);

					for (BlIn_BillCalcResponseBillItemObject billItemObj : billServiceTypeObj.BillItems) {
						
    					recordsToInsert.add(new BillItem__c(
    														Name = billItemObj.Name, 
    														BillServiceType__r = billServiceTypeReference, 
															HerokuPostgresId__c = billItemObj.Id + rand, 
															ServiceItem__c = (Id)billItemObj.ServiceItemId, 
//															BillItem__c = (Id)billItemObj.BillItemId, 
//															RateBand__c = (Id)billItemObj.RateBandId, 
//															Reading__c = (Id)billItemObj.ReadingId, 
															VolumeUsed__c = Integer.valueOf(billItemObj.VolumeUsed), 
															From__c = Date.valueOf(billItemObj.FromDate), 
															To__c = Date.valueOf(billItemObj.ToDate), 
															BilledAmount__c = Decimal.valueOf(billItemObj.BilledAmount)
															)
											);
					}
				}
				
    		}
    		
    		// save the records
			Database.SaveResult[] results = Database.insert(recordsToInsert);

			// and check the results
			for (Integer i = 0; i < results.size(); i++) {

				if (results[i].isSuccess()) {
					System.debug(DEBUG + 'Created record with Id: ' + results[i].getId());

				} else {
					System.debug(DEBUG + 'Error: could not create record ' + 'for array element ' + i + '.');
					System.debug('The error reported was: ' + results[i].getErrors()[0].getMessage() + '\n');
    				return null;
				}
			}
			
			// return a list of the Ids of the bill records inserted
			List<Id> billIds = new List<Id>();
			for (Bill__c bill : billsInserted) {
				billIds.add(bill.Id);
			}
			return billIds;
    	}
    	return null;
    }
}