src/objects/Bill__c.object
<CustomObject>
    <fields>
        <fullName>BillCalculation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>18 Sep 2017, P Dixon - lookup to bill calculation record created if this bill was calculated as part of a manual request</description>
        <label>Bill Calculation</label>
        <referenceTo>BillCalculation__c</referenceTo>
        <relationshipLabel>Bills</relationshipLabel>
        <relationshipName>Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BillDate__c</fullName>
        <description>This is the Date that the Bill was generated on.</description>
        <label>Bill Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Number</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Bills</relationshipLabel>
        <relationshipName>Bills</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bill</label>
    <nameField>
        <label>Bill</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BillCalculation__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>11 Sep 2017, P Dixon - The status of a bill calculation request</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Bill Calculation</label>
    <nameField>
        <displayFormat>BC-{00000000}</displayFormat>
        <label>Bill Calculation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>BillCalculation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>18 Sep 2017, P Dixon - lookup to bill calculation request record to track whether a manual bill calculation has been requested</description>
        <label>Bill Calculation</label>
        <referenceTo>BillCalculation__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LastBillCalculationDate__c</fullName>
        <description>Updated by the Bill Date of the last bill. Hide from page layout. Used for calculation only.</description>
        <label>Last Bill Calculation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(TODAY()&lt; ContractStartDate__c ,&apos;Not Started&apos;, 
IF(OR(AND(TODAY()&gt;=ContractStartDate__c,ISBLANK( ContractEndDate__c )), AND(ContractStartDate__c&lt;=TODAY(),TODAY()&lt;=ContractEndDate__c)) ,&apos;Active&apos;, 
IF(AND(TODAY()&gt;ContractEndDate__c, CustomerName__r.TotalLedgerAmount__c &gt;0), &apos;Inactive(with Debt)&apos;,  
IF(AND(TODAY()&gt;ContractEndDate__c, CustomerName__r.TotalLedgerAmount__c =0), &apos;Inactive(no Debt)&apos;,&apos;Inactive(with Credit)&apos;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>CON-{00000000}</displayFormat>
        <label>Contract Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GlUt_BillHandler.cls
/******************************************************************************
@author    		Accenture: Patrick Dixon
@date      		21 Sep 2017
@description 	Handler for Bill trigger
*******************************************************************************/
public with sharing class GlUt_BillHandler extends GlUt_TriggerHandlerBase {
	
	// Maps of the related records that will be updated by this trigger
	Map<Id, Contract__c> contractsToUpdate;
	Map<Id, BillCalculation__c> billCalculationsToUpdate;
	
	/******************************************************************************
	@author    		Accenture: Patrick Dixon
	@date      		21 Sep 2017
	@param			Id - contract Id
    @param          GlUt_TriggerHandlerObj - inputParam
    @description	This method handles the initial invocation of the trigger
	*******************************************************************************/
    public override void MainEntry(GlUt_TriggerHandlerObj inputParam) {

		// initialise related records maps
		contractsToUpdate = new Map<Id, Contract__c>();
		billCalculationsToUpdate = new Map<Id, BillCalculation__c>();

        try {
        	// TO-DO Logger.Push('MainEntry', 'GlUt_AccountHandler');
        	
        	/* This is a Heroku mastered object so we shouldn't be modifying any fields on it */
        	/* Therfore before Insert/Update triggers not required */
        		
            if (inputParam.isInsert && inputParam.isAfter) {
            	
            	// update fields on related records
            	updateRelatedRecords(inputParam.newmap);
            }
            
            if (inputParam.isUpdate && inputParam.isAfter) {
            }
            
            if (inputParam.isDelete && inputParam.isBefore) {
            }
            
            if (inputParam.isDelete && inputParam.isAfter) {
            }
            
        } catch (exception e) {
			// TO-DO Logger.debugException(e);
        }

        finally {
        	
        	// update the related records
        	if (!contractsToUpdate.isEmpty()) update contractsToUpdate.values();
        	if (!billCalculationsToUpdate.isEmpty()) update billCalculationsToUpdate.values();
        	
            // Reset the active function to null in case this class was first in stack
            // this indicates that the trigger has finished firing so it no longer needs to control flow
            GlUt_CentralDispatcher.activeFunction = null;
            // TO-DO Logger.pop();
        }
	}
	
	/******************************************************************************
	@author    		Accenture: Patrick Dixon
	@date      		21 Sep 2017
	@param			Map<Id, SObject> - newMap
	@description 	Updates LastBillCalculationDate on Contract__c and
					Status = 'Completed' on BillCalculation for new Bills inserted
	*******************************************************************************/
	public void updateRelatedRecords(Map<Id, SObject> newMap) {
		
		Map<Id, Date> contractBillDateMap = new Map<Id, Date>();		// map of bill dates keyed on contract Id
		List<Id> billCalculationIdsToUpdate = new List<Id>();		// list of related bill calculation Ids

		// get the related contract and bill calculation records
		for (Bill__c bill : (List<Bill__c>)newMap.values()) {
			
			contractBillDateMap.put(bill.ContractNumber__c, bill.BillDate__c);
			billCalculationIdsToUpdate.add(bill.BillCalculation__c);
		}
		
		// for each related contract
		for (Contract__c contract : [select Id, 
											LastBillCalculationDate__c
									from Contract__c
									where Id in :contractBillDateMap.keySet()]) {
			
			// if the new bill date is more recent than the last bill calculation date, update it
			if (contract.LastBillCalculationDate__c == null 
					|| contract.LastBillCalculationDate__c < contractBillDateMap.get(contract.Id)) {
				contract.LastBillCalculationDate__c = contractBillDateMap.get(contract.Id);
				
				// and add it to the update map
				contractsToUpdate.put(contract.Id, contract);
			}

		}
		
		// for each related bill calculation
		for (BillCalculation__c billCalculation : [select Id, 
														Status__c
													from BillCalculation__c
													where Id in :billCalculationIdsToUpdate]) {
			
			// ensure the bill calculation status is 'Completed'								
			billCalculation.Status__c = BlIn_Constants.BILL_CALCULATION_STATUS_COMPLETED;						
			billCalculationsToUpdate.put(billCalculation.Id, billCalculation);
		}
	}
}