src/objects/BillCalculation__c.object
<CustomObject>
    <label>Bill Calculation</label>
    <nameField>
        <displayFormat>BC-{00000000}</displayFormat>
        <label>Bill Calculation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>BillCalculation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>18 Sep 2017, P Dixon - lookup to bill calculation request record to track whether a manual bill calculation has been requested</description>
        <label>Bill Calculation</label>
        <referenceTo>BillCalculation__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BillingAddress__c</fullName>
        <description>Pre-populate the field from Billing Address on Customer. Allow the user to overwrite.</description>
        <label>Billing Address</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BillingFrequency__c</fullName>
        <description>This field differentiate the frequency of Billing life cycle.</description>
        <label>Billing Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Six Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DebtRecoveryProfile__c</fullName>
        <label>Debt Recovery Profile</label>
        <picklist>
            <picklistValues>
                <fullName>Standard HH Debt Recovery Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard NHH Debt Recovery Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Profile 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Profile 2</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>CON-{00000000}</displayFormat>
        <label>Contract Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BlIn_BillCalcExtractData_Test.cls
/******************************************************************************
@author:      Accenture: Sucharu Gupta
@date:        05 September 2017
@description: Test Class for BlIn_BillCalcExtractData 
*******************************************************************************/

@isTest
//test data creation for BlIn_BillCalcExtractData class
Public Class BlIn_BillCalcExtractData_Test{
    
    private static string DEBT_RECOVERY_PROFILE = 'Standard HH Debt Recovery Process';
    private static string BILLING_FREQUENCY = 'Monthly';
    private static string BILLING_ADDRESS = 'Test Address';
    private static string PROFILE_NAME = 'System Administrator';
    private static String USER_PROFILE ='System Administrator';
    private static String USER_NAME ='TestUser'; 
    private static String ACCOUNT_NAME = 'TestAccount'; 
    private static String CONTRACT_NAME_ONE ='TestContract';
    private static String CONTRACT_NAME_SECOND ='TestContract2';
    
/*******************************************************************
Purpose: method to create test data used by all test methods
Parameters: N/A 
Returns: void
Throws [Exceptions]: N/A
********************************************************************/
    
    @TestSetup
    Static void createTestData(){
        
        User objUser = GlUt_TestFactoryData.createUser(USER_PROFILE ,USER_NAME ,null);
        Database.insert(objUser); 
        
        Account objAccount = GlUt_TestFactoryData.CreateAccount(ACCOUNT_NAME );
        Database.insert(objAccount);
        BillCalculation__c objBillCalculation = GlUt_TestFactoryData.createBillCalculation();
        Database.insert(objBillCalculation);
        
        list<Contract__c >lstContract = new list<Contract__c>(); 
        
        Contract__c con = GlUt_TestFactoryData.CreateContract(CONTRACT_NAME_ONE ,objAccount); 
        con.DebtRecoveryProfile__c = DEBT_RECOVERY_PROFILE;
        con.BillingFrequency__c = BILLING_FREQUENCY;
        con.BillingAddress__c = BILLING_ADDRESS;
        con.BillCalculation__c = objBillCalculation.id;
        lstContract.add(con);
        
        Contract__c con2 = GlUt_TestFactoryData.CreateContract(CONTRACT_NAME_SECOND ,objAccount);
        con2.DebtRecoveryProfile__c = DEBT_RECOVERY_PROFILE;
        con2.BillingFrequency__c = BILLING_FREQUENCY;
        con2.BillingAddress__c = BILLING_ADDRESS;
        con2.BillCalculation__c = objBillCalculation.id;

        lstContract.add(con2);
        
        Database.insert(lstContract);
    }
    

    
/*******************************************************************
Purpose: Method to test Retrives and packages billing data (List of ID'S) {Positive scenario}
Parameters: N/A 
Returns: void
Throws [Exceptions]: N/A
********************************************************************/
    
    static testmethod void retriveDataListContract_Positive(){
        User objUser =[select id,name from user where isActive=true limit 1];
        Contract__c con =[Select id,name from Contract__c limit 1];
        BillCalculation__c objBillCalculation = [select id from BillCalculation__c];
        Id billCalculationId = objBillCalculation .id;
        List<Id> lstContractIds = new List<Id>();
        lstContractIds.add(con.id);
        system.runas(objUser){
            Test.startTest();
            String str1 = BlIn_BillCalcExtractData.retrieveData(billCalculationId);
            Test.StopTest();
            system.assertNotEquals(null,str1);
        }
        
    }
    

}