src/objects/Contract__c.object
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>CON-{00000000}</displayFormat>
        <label>Contract Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Suppression__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Suppressions</relationshipLabel>
        <relationshipName>Suppressions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Suppression</label>
    <nameField>
        <displayFormat>SID-{00000000}</displayFormat>
        <label>Suppression ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppressions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BlAp_Constants.cls
/************************************************************************************************************
@author         Accenture : Luke Emberton
@date           09-Sep-2017
@description:   This is the constants class for all static strings used in this namespace
**************************************************************************************************************/
public class BlAp_Constants {
    
    //The prefix for this namespace
    public static string PREFIX = 'BlAp_';
    
    //Appended to the end of all trigger handler classes
    public static string  CONTRACTAPINAME                    = 'Contract__c';
    public static string  SUPRESSIONAPINAME                    = 'Suppression__c';

}