src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <description>Match to salesforce Address format</description>
        <label>City</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationReference__c</fullName>
        <formula>Name &amp;TEXT( LocationValidation__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Reference</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationSubType__c</fullName>
        <description>Dependent on Location Type</description>
        <label>Location Sub Type</label>
        <picklist>
            <controllingField>LocationType__c</controllingField>
            <picklistValues>
                <fullName>Detached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi detached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terraced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Croft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Factory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Sector</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LocationType__c</fullName>
        <description>Can be used for customer linking validation</description>
        <label>Location Type</label>
        <picklist>
            <picklistValues>
                <fullName>Domestic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ParentLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to establish a relationship between Locations.</description>
        <label>Parent Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Child Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PostalZIPCode__c</fullName>
        <label>Postal/ZIP Code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StateProvince__c</fullName>
        <description>Match to salesforce Address format</description>
        <label>State/Province</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Match to salesforce Address format</description>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <label>Location</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CuAp_AddressPageController.cls
public with sharing class CuAp_AddressPageController {
	
	private static List<string> locFields;
	
	static{
			//Get Fields from the Supression Object
		 	locFields = new List<string>();
		 	locFields.add('Street__c');
		 	locFields.add('City__c');
		 	locFields.add('StateProvince__c');
		 	locFields.add('PostalZIPCode__c');
		 	locFields.add('ParentLocation__c');
		 	locFields.add('LocationType__c');
		 	locFields.add('LocationSubType__c');
		 	locFields.add('LocationReference__c');
		 		 	
	}

	
	/**********************************************************************************************
	@author      	Accenture: Luke Emberton
	@date      		04-Sep-2017
	@return			List<GLAp_FieldProps>
	@description		This method returns the field properties for each of the fields that are
					to be displayed on the screen
	**********************************************************************************************/
	 @AuraEnabled
	public static List<GLAp_FieldProps> retrieveLocationPropDetails() {
		
		//Get the field properties for the supression object
	 	List<GLAp_FieldProps> locProps = GlAp_LightningDataAccess.getObjectsFieldProperties(CuAp_Constants.LOCATIONAPINAME, locFields);	 	
	 	
	 	//Want to make all of the contract fields readonly
	 	for(GLAp_FieldProps locProp: locProps){
	 		locProp.isEditable = false;
	 	}

 		return locProps;
		
	}
	
	
	/**********************************************************************************************
	@author      	Accenture: Luke Emberton
	@date      		10-Sep-2017
	@return			List<BlAp_CombinedRecord>
	@description		This method returns the field properties for each of the fields that are
					to be displayed on the screen
	**********************************************************************************************/
	
	@AuraEnabled
	public static List<BlAp_CombinedRecord> queryForLocations(string sPostCode, string sState, string sStreet, string sCity) {
	
		List<BlAp_CombinedRecord>  locationSelectList = new List<BlAp_CombinedRecord>();
	 	
		boolean performQuery = true;
		//Only query datbase if one field is field in
		if((sPostCode == null || sPostCode =='') && (sState == null ||sState =='') &&(sStreet == null || sStreet =='') &&(sCity == null ||sCity =='') ){
				performQuery = false;	
			}
		
		if(performQuery){
			string sOQLQuery ='';
		 	
		 	//Build up start of SOQL Query
		 	sOQLQuery = String.format('SELECT {0} FROM {1}', new List<String>{'Id,' + String.join(locFields,','), CuAp_Constants.LOCATIONAPINAME +' WHERE '});
		 	
		 	boolean isStart = true;
		 	//Add all of the input parameters to the searcg string
		 	if(sPostCode != null && sPostCode!=''){
		 		sOQLQuery += appendLikeClause('PostalZIPCode__c', sPostCode, isStart);
		 		isStart = false;
		 	}
		 	
		 	else if(sStreet != null && sStreet!=''){
		 		sOQLQuery += appendLikeClause('Street__c', sStreet, isStart);
		 		isStart = false;
		 	}
		 	else if(sCity != null && sCity!=''){
		 		sOQLQuery += appendLikeClause('City__c', sCity, isStart);
		 		isStart = false;
		 	}
		 	else if(sState != null && sState!=''){
		 		sOQLQuery += appendLikeClause('StateProvince__c', sState, isStart);
		 		isStart = false;
		 	}
		 	
		 	system.debug('sOQLQuery: ' + sOQLQuery);
		 	List<Location__c> locationList = Database.query(sOQLQuery);
		 	
		 	//Check the security on the location fields
	 		locationList = GlUt_FieldSecurity.cleanseFields(locationList, locFields, true);
		 	
		 	//Loop throught the contract list and capture the appropriate suppresion information
		 	for(Location__c loc : locationList){
		 		
		 		BlAp_CombinedRecord locationSelectRecord = new BlAp_CombinedRecord();	 		
		 		
		 		locationSelectRecord.uniqueId=loc.Id;
		 		locationSelectRecord.isSelected = false;
		 		locationSelectRecord.objectMap = new Map<string, sObject>();
		 		locationSelectRecord.objectMap.put(CuAp_Constants.LOCATIONAPINAME, loc);	 			 			 		
		 		locationSelectList.add(locationSelectRecord);
		 		
		 	}
		}
	 	return locationSelectList;
	}
	
	private static string appendLikeClause(string fieldName, string fieldVal, boolean isStart){
		string retVal;
		if(isStart){
			retVal = fieldName + ' LIKE \'%' + fieldVal + '%\'';
		}
		else{
			retVal = ' OR ' + fieldName + ' LIKE \'%' + fieldVal + '%\'';
		}
		return retVal;
	}
    
}